### ISSUE TITLE
How to animate keys?

### ISSUE THREAD

**Issue by henry-95** [ChromaSDK/quickstart-sample#3]
Hey, this project is great and really helpful.
I've gone through the keyboard 2d matrix/array light effect, however I'm not sure how to animate the lights over time. 
For example, take this bit of code in the Template.cpp file:

```
for (UINT row = 0; row < ChromaSDK::Keyboard::MAX_ROW; row++) {
		for (UINT col = 0; col < ChromaSDK::Keyboard::MAX_COLUMN; col++) {
			Example_keyboard_effect.Color[row][col] = ORANGE;   //Filling the whole matrix with the color orange == Setting background to orange
		}
	}
RZRESULT Result_Keyboard = CreateKeyboardEffect(ChromaSDK::Keyboard::CHROMA_CUSTOM, &Example_keyboard_effect, nullptr);
```

How would you animate that so it applies the effect after each step in the for loop?

**Comment by tngebauer** [comment]
Hey there,
sorry for the delayed answer. 
If you are still interested in a solution for your problem, you could simply run the 
`RZRESULT Result_Keyboard = CreateKeyboardEffect(ChromaSDK::Keyboard::CHROMA_CUSTOM, &Example_keyboard_effect, nullptr);` 
within one of the two for-loops depending on what animation you want.
